### ISSUE TITLE
Control button on most pages are unaligned

### ISSUE THREAD

**Issue by The-CJ** [The-CJ/Phaazebot#143]
maybe add something like this?

```css
.center-item-row .icon-btn:first-child {margin-left: 0}
.center-item-row .icon-btn:last-child {margin-right: 0}
```
but maybe secure this with a extra class before `.control` or so?
